name: Refresh to latest Docker images on NERSC Spin

on:
  repository_dispatch:
    types: [trigger-workflow-release-to-spin]

jobs:
  rancher_job:
    runs-on: ubuntu-latest
    steps:
      - name: restart fastapi
        uses: colbyhill21/Rancher-Action@1.1
        with: 
          args: '"rollout restart deployment/runtime-fastapi --namespace=nmdc-dev"'
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
      - name: restart dagit
        uses: colbyhill21/Rancher-Action@1.1
        with: 
          args: '"rollout restart deployment/dagit --namespace=nmdc-dev"'
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
      - name: restart dagster-daemon
        uses: colbyhill21/Rancher-Action@1.1
        with: 
          args: '"rollout restart deployment/dagster-daemon --namespace=nmdc-dev"'
          token: ${{ secrets.RANCHER_TOKEN }}
          context: ${{ secrets.RANCHER_CONTEXT }}
          url: ${{ secrets.RANCHER_URL }}
